import type { Locale } from "@/lib/types";

export type GrowTip = {
  title: string;
  body: string;
};

const arTips: GrowTip[] = [
  {
    title: "شيّع وارقد",
    body: "السمعة الجيدة هي رأس مالك الحقيقي. ركّز أولاً على جودة عملك وطريقة تعاملك، وبعدها ستأتيك الطلبات بشكل طبيعي.",
  },
  { title: "السمعة", body: "السمعة الطيبة تجيب لك الزبون قبل الإعلان." },
  { title: "أول انطباع", body: "أول انطباع يبدأ من صورتك وطريقة ردّك." },
  { title: "وضوح السعر", body: "وضوحك في السعر يريحك ويزيد ثقة الزبون." },
  { title: "الالتزام", body: "لا تعد بما لا تستطيع إنجازه." },
  { title: "الجودة أولاً", body: "الجودة أهم من الكمية في البداية." },
  { title: "الثقة", body: "الزبون يشتري الثقة قبل الخدمة." },
  { title: "سرعة الرد", body: "ردّك السريع يعطي انطباعاً بالجدية." },
  { title: "الكلمة الطيبة", body: "الكلمة الطيبة تفتح أبواباً كثيرة." },
  { title: "احترام الوقت", body: "احترم وقت الزبون ليحترم وقتك." },
  { title: "التفاصيل", body: "التفاصيل الصغيرة تصنع فرقاً كبيراً." },
  { title: "انتشار السمعة", body: "سمعتك تنتشر أسرع من إعلانك." },
  { title: "العمل النظيف", body: "العمل النظيف يتكلم عن نفسه." },
  { title: "الرد الواضح", body: "لا تترك زبوناً بدون رد واضح." },
  { title: "الوضوح", body: "كن واضحاً منذ البداية لتجنب المشاكل." },
  { title: "الصورة", body: "الصورة الجيدة نصف الإقناع." },
  { title: "الاتفاق", body: "الاتفاق الواضح يحميك ويحمي الزبون." },
  { title: "نطاق العمل", body: "حدّد ما يشمله العمل وما لا يشمله." },
  { title: "قبل البداية", body: "لا تبدأ العمل قبل الاتفاق على السعر." },
  { title: "المواعيد", body: "كن دقيقاً في المواعيد." },
  { title: "عند التأخير", body: "إذا تأخرت، أخبر الزبون مسبقاً." },
  { title: "الاحترام", body: "تعامل باحترام حتى عند الاختلاف." },
  { title: "هدوءك", body: "لا تأخذ كل شيء بشكل شخصي." },
  { title: "التنظيم", body: "التنظيم يوفر عليك وقتاً وجهداً." },
  { title: "الفهم أولاً", body: "اسأل لتفهم قبل أن تنفذ." },
  { title: "المهنية", body: "المهنية هي ما يميزك عن غيرك." },
  { title: "اللباقة", body: "اللباقة في الكلام جزء من الخدمة." },
  { title: "التوضيح", body: "التوضيح أفضل من الافتراض." },
  { title: "الرضا", body: "لا تترك العمل قبل التأكد من رضا الزبون." },
  { title: "الصراحة", body: "كن صريحاً إذا كنت لا تستطيع تنفيذ الطلب." },
  { title: "الاحتراف", body: "الاحترافية تظهر في التفاصيل." },
  { title: "البداية", body: "البداية قد تكون صغيرة لكن الاستمرار يصنع الفرق." },
  { title: "كل زبون", body: "كل زبون فرصة لزبائن آخرين." },
  { title: "أفضل إعلان", body: "الزبون الراضي أفضل إعلان." },
  { title: "حسن العرض", body: "حسن عرضك يزيد فرصك." },
  { title: "بداية بسيطة", body: "لا تخف من البداية البسيطة." },
  { title: "خطوة خطوة", body: "طوّر نفسك خطوة خطوة." },
  { title: "من التجربة", body: "كل تجربة تعلمك شيئاً." },
  { title: "الاستمرارية", body: "الاستمرارية أهم من الكمال." },
  { title: "من الأخطاء", body: "تعلّم من الأخطاء ولا تتوقف." },
  { title: "الصبر", body: "النجاح يحتاج صبراً." },
  { title: "تكرار الطلب", body: "الجودة تجلب تكرار الطلب." },
  { title: "الزبون العائد", body: "الزبون الذي يعود كنز." },
  { title: "رأي الزبون", body: "اسأل الزبائن عن رأيهم بعد الخدمة." },
  { title: "التطور", body: "التطور لا يحدث في يوم واحد." },
  { title: "الاستثمار", body: "استثمر في تحسين عملك." },
  { title: "الخصوصية", body: "لا تشارك معلوماتك الشخصية بدون حاجة." },
  { title: "حماية الخصوصية", body: "احمِ خصوصيتك دائماً." },
  { title: "عدم الارتياح", body: "إذا شعرت بعدم الارتياح، توقف." },
  { title: "الطلب الغامض", body: "لا توافق على طلب غير واضح." },
  { title: "توثيق المحادثات", body: "احتفظ بالمحادثات المهمة في مكان يمكن الرجوع إليه." },
  { title: "التحويلات", body: "لا تقبل تحويلات مشبوهة." },
  { title: "حدسك", body: "ثق بحدسك عندما يكون هناك شيء غير مريح." },
  { title: "الحدود", body: "حدّد حدودك بوضوح." },
  { title: "الظروف الآمنة", body: "لا تعمل في ظروف غير آمنة." },
  { title: "السلامة", body: "السلامة أولاً دائماً." },
  { title: "تفاصيل الطلب", body: "تأكد من تفاصيل الطلب قبل الموافقة." },
  { title: "إرضاء الجميع", body: "لا تضغط على نفسك لإرضاء الجميع." },
  { title: "وقتك", body: "احمِ وقتك كما تحمي عملك." },
  { title: "التبليغ", body: "التبليغ يحميك ويحمي الآخرين." },
  { title: "صورة أوضح", body: "صورة واضحة قد تجلب طلبات أكثر." },
  { title: "أفضل الأعمال", body: "أظهر أفضل أعمالك أولاً." },
  { title: "الوصف", body: "اكتب وصفاً بسيطاً وواضحاً." },
  { title: "الاختصار", body: "لا تكثر الكلام، وضّح المهم." },
  { title: "عرض السعر", body: "اعرض السعر بطريقة مفهومة." },
  { title: "سهولة التواصل", body: "اجعل تواصلك سهلاً وواضحاً." },
  { title: "لغة بسيطة", body: "استخدم لغة بسيطة يفهمها الجميع." },
  { title: "اكتمال الملف", body: "لا تترك معلومات ناقصة في ملفك." },
  { title: "مراجعة الملف", body: "راجع ملفك قبل نشره." },
  { title: "التقييم", body: "اطلب تقييماً بعد انتهاء العمل." },
  { title: "المتابعة", body: "تابع مع الزبون بعد الخدمة عندما يكون ذلك مناسباً." },
  { title: "الترتيب", body: "الترتيب يعكس الاحتراف." },
  { title: "اختصار الطريق", body: "اختصر الطريق على الزبون ووضّح له المطلوب." },
  { title: "خطوات العمل", body: "وضّح خطوات العمل من البداية." },
  { title: "التوفر", body: "كن متاحاً بشكل منظم، لا بشكل مرهق." },
  { title: "دلالة الناس", body: "اللي يخدم مليح، الناس تدل عليه." },
  { title: "الخير", body: "الخير يرجع لصاحبه." },
  { title: "الفرج", body: "الصبر مفتاح الفرج." },
  { title: "إيجاد الطريق", body: "اللي يحب يخدم، يلقى طريق." },
  { title: "الأثر", body: "الخدمة النظيفة تبقى." },
  { title: "قبل الحاجة", body: "الناس تشري الثقة قبل الحاجة." },
  { title: "البركة", body: "اليد اللي تخدم تتبارك." },
  { title: "حسن الكلام", body: "الكلمة الطيبة صدقة." },
  { title: "قيمة العمل", body: "اللي يعطي قيمة لعمله، الناس تعطيه قيمة." },
  { title: "الاستعجال", body: "ما يضيع غير اللي يستعجل." },
  { title: "البساطة", body: "الزين يبان ولو كان بسيطاً." },
  { title: "النتيجة", body: "الخدمة تبان في نتيجتها." },
  { title: "الضمير", body: "اللي يخدم بضمير يربح." },
  { title: "يوماً بيوم", body: "السمعة تبنيها يوم بيوم." },
  { title: "الوضوح والاحترام", body: "الثقة تُبنى بالوضوح والاحترام." },
  { title: "القدرة", body: "أنت قادر على تطوير عملك." },
  { title: "أهم خطوة", body: "البداية أهم خطوة." },
  { title: "المقارنة", body: "لا تقارن نفسك بالآخرين كثيراً." },
  { title: "تقدمك", body: "ركّز على تقدمك أنت." },
  { title: "كل خطوة", body: "كل خطوة تحسب." },
  { title: "ابدأ الآن", body: "لا تنتظر الكمال حتى تبدأ." },
  { title: "ابدأ بما لديك", body: "ابدأ بما لديك وطوّره مع الوقت." },
  { title: "التجربة", body: "الثقة تأتي مع التجربة." },
  { title: "النَفَس", body: "النجاح يحتاج وقتاً ونَفَساً." },
  { title: "مستقبلك", body: "أنت تبني مستقبلك بيدك." },
];

const frTips: GrowTip[] = [
  {
    title: "Faites-vous connaître par la qualité",
    body: "Votre réputation est votre vrai capital. Soignez votre travail et votre manière de traiter les clients, puis les demandes viendront plus naturellement.",
  },
  { title: "Réputation", body: "Une bonne réputation attire les clients avant même la publicité." },
  { title: "Première impression", body: "La première impression commence par votre photo et votre première réponse." },
  { title: "Prix clairs", body: "Des prix clairs rassurent et inspirent confiance." },
  { title: "Promesses réalistes", body: "Ne promettez pas ce que vous ne pouvez pas livrer." },
  { title: "Qualité d'abord", body: "Au début, la qualité compte plus que la quantité." },
  { title: "Confiance", body: "Le client achète d’abord la confiance." },
  { title: "Réactivité", body: "Une réponse rapide donne une impression de sérieux." },
  { title: "Respect", body: "Un mot respectueux ouvre beaucoup de portes." },
  { title: "Temps du client", body: "Respectez le temps du client pour qu’il respecte le vôtre." },
  { title: "Détails", body: "Les petits détails font une grande différence." },
  { title: "Bouche-à-oreille", body: "Votre réputation circule plus vite que votre publicité." },
  { title: "Travail soigné", body: "Un travail soigné parle pour vous." },
  { title: "Réponse nette", body: "Ne laissez pas un client sans réponse claire." },
  { title: "Clarté", body: "Soyez clair dès le départ pour éviter les problèmes." },
  { title: "Bonne photo", body: "Une bonne photo renforce la confiance." },
  { title: "Accord clair", body: "Un accord clair vous protège, vous et le client." },
  { title: "Périmètre", body: "Précisez ce que le service comprend et ne comprend pas." },
  { title: "Avant de commencer", body: "Ne commencez pas avant d’avoir clarifié le prix." },
  { title: "Ponctualité", body: "Soyez ponctuel." },
  { title: "Retard", body: "En cas de retard, prévenez à l’avance." },
  { title: "Désaccord", body: "Restez respectueux, même en cas de désaccord." },
  { title: "Distance", body: "Ne prenez pas tout de manière personnelle." },
  { title: "Organisation", body: "L’organisation vous fait gagner du temps et de l’énergie." },
  { title: "Comprendre", body: "Posez des questions pour bien comprendre avant d’agir." },
  { title: "Professionnalisme", body: "Le professionnalisme vous distingue." },
  { title: "Politesse", body: "La politesse fait partie du service." },
  { title: "Clarifier", body: "Mieux vaut clarifier que supposer." },
  { title: "Vérifier", body: "Ne partez pas avant de vérifier que le client a bien compris ou est satisfait." },
  { title: "Honnêteté", body: "Soyez honnête si vous ne pouvez pas accepter la demande." },
  { title: "Détails utiles", body: "Le professionnalisme se voit dans les détails." },
  { title: "Petit début", body: "Un petit début peut mener à de grandes opportunités." },
  { title: "Chaque client", body: "Chaque client peut en amener d’autres." },
  { title: "Meilleure publicité", body: "Un client satisfait est votre meilleure publicité." },
  { title: "Présentation", body: "Une meilleure présentation augmente vos chances." },
  { title: "Commencer simplement", body: "N’ayez pas peur de commencer simplement." },
  { title: "Pas à pas", body: "Avancez pas à pas." },
  { title: "Apprendre", body: "Chaque expérience vous apprend quelque chose." },
  { title: "Régularité", body: "La régularité compte plus que la perfection." },
  { title: "Erreurs", body: "Apprenez de vos erreurs sans vous arrêter." },
  { title: "Patience", body: "La réussite demande de la patience." },
  { title: "Demandes répétées", body: "La qualité favorise les demandes répétées." },
  { title: "Client fidèle", body: "Un client qui revient est précieux." },
  { title: "Retour client", body: "Demandez un retour après le service." },
  { title: "Progression", body: "La progression ne se fait pas en un jour." },
  { title: "Amélioration", body: "Investissez dans l’amélioration de votre activité." },
  { title: "Infos personnelles", body: "Ne partagez pas vos informations personnelles sans raison." },
  { title: "Vie privée", body: "Protégez toujours votre vie privée." },
  { title: "Malaise", body: "Si une situation vous met mal à l’aise, arrêtez-vous." },
  { title: "Demande floue", body: "N’acceptez pas une demande floue." },
  { title: "Échanges utiles", body: "Gardez les échanges importants dans un canal facile à retrouver." },
  { title: "Transferts suspects", body: "Refusez les transferts suspects." },
  { title: "Intuition", body: "Faites confiance à votre intuition lorsqu’un échange semble étrange." },
  { title: "Limites", body: "Fixez vos limites clairement." },
  { title: "Conditions sûres", body: "N’acceptez pas de travailler dans des conditions peu sûres." },
  { title: "Sécurité", body: "La sécurité passe toujours en premier." },
  { title: "Détails avant accord", body: "Vérifiez bien les détails avant d’accepter." },
  { title: "Équilibre", body: "Ne vous épuisez pas à vouloir satisfaire tout le monde." },
  { title: "Protéger votre temps", body: "Protégez votre temps comme vous protégez votre travail." },
  { title: "Signaler", body: "Signaler un problème peut vous protéger, vous et les autres." },
  { title: "Photo claire", body: "Une photo claire peut attirer plus de demandes." },
  { title: "Meilleurs travaux", body: "Montrez d’abord vos meilleurs travaux." },
  { title: "Description", body: "Écrivez une description simple et claire." },
  { title: "Aller à l’essentiel", body: "Allez à l’essentiel." },
  { title: "Présenter vos prix", body: "Présentez vos prix de façon compréhensible." },
  { title: "Communication simple", body: "Rendez votre communication simple et claire." },
  { title: "Langage simple", body: "Utilisez un langage facile à comprendre." },
  { title: "Profil complet", body: "Ne laissez pas votre profil incomplet." },
  { title: "Relire", body: "Relisez votre profil avant de le publier." },
  { title: "Demander un avis", body: "Demandez un avis après une mission réussie." },
  { title: "Recontacter", body: "Recontactez le client après le service quand c’est pertinent." },
  { title: "Profil organisé", body: "Un profil bien organisé inspire davantage confiance." },
  { title: "Compréhension", body: "Facilitez la compréhension du service pour le client." },
  { title: "Étapes du service", body: "Expliquez les étapes du service dès le départ." },
  { title: "Disponibilité", body: "Soyez disponible de manière organisée, pas au détriment de votre équilibre." },
  { title: "Bouche-à-oreille local", body: "Quand le travail est bon, les gens en parlent." },
  { title: "Faire le bien", body: "Le bien revient à celui qui le fait." },
  { title: "Patience utile", body: "La patience porte ses fruits." },
  { title: "Trouver son chemin", body: "Celui qui veut vraiment avancer finit par trouver son chemin." },
  { title: "Trace durable", body: "Un travail propre laisse une trace durable." },
  { title: "Avant le besoin", body: "Les gens achètent la confiance avant le besoin." },
  { title: "Travail sérieux", body: "Une main qui travaille avec sérieux est bénie." },
  { title: "Parole bienveillante", body: "Une parole bienveillante a de la valeur." },
  { title: "Valeur du travail", body: "Quand vous respectez la valeur de votre travail, les autres la respectent aussi." },
  { title: "Se précipiter", body: "Se précipiter fait souvent perdre en qualité." },
  { title: "Simplicité", body: "Ce qui est bien fait se voit, même dans la simplicité." },
  { title: "Résultat", body: "La qualité se voit dans le résultat." },
  { title: "Conscience", body: "Travailler avec conscience finit par payer." },
  { title: "Jour après jour", body: "Une réputation se construit jour après jour." },
  { title: "Clarté et respect", body: "La confiance se construit avec clarté et respect." },
  { title: "Vous pouvez", body: "Vous pouvez faire progresser votre activité." },
  { title: "Commencer", body: "Commencer est déjà une grande étape." },
  { title: "Comparaison", body: "Évitez de trop vous comparer aux autres." },
  { title: "Votre progression", body: "Concentrez-vous sur votre propre progression." },
  { title: "Chaque étape", body: "Chaque étape compte." },
  { title: "Sans attendre", body: "N’attendez pas la perfection pour commencer." },
  { title: "Avec ce que vous avez", body: "Commencez avec ce que vous avez et améliorez-le avec le temps." },
  { title: "Expérience", body: "La confiance vient avec l’expérience." },
  { title: "Constance", body: "La réussite demande du temps et de la constance." },
  { title: "Votre avenir", body: "Vous construisez votre avenir par vos efforts." },
];

export function getGrowTips(locale: Locale) {
  return locale === "ar" ? arTips : frTips;
}
